View(WWWusage)
nrow(WWWusage)
ncol(WWWusage)
dim(WWWusage)
names(WWWusage)
str(WWWusage)
attributes(WWWusage)
head(WWWusage, 10) 
tail(WWWusage, 10)
WWWusage[1:10]
summary(WWWusage)
mean(Titanic)
median(Titanic)
range(Titanic)
quantile(Titanic)
quantile(Titanic, c(.1, .3, .65))
var(Titanic)
table(Titanic)
pie(table(Titanic))
barplot(table(JohnsonJohnson))


hist(JohnsonJohnson)
plot(density(JohnsonJohnson))
aggregate(Sex ~ Freq, summary, data=Titanic)
#BOXPLOT
boxplot(Class~ Freq, data=Titanic)
#SCATTERPLOT
with(HairEyeColor, plot(Eye, Freq, col=Eye,pch=as.numeric(Eye)))
plot(jitter(HairEyeColor), jitter(HairEyeColor))
pairs(HairEyeColor)
#3DSCATTERPLOT 
install.packages("scatterplot3d")
library(scatterplot3d)
scatterplot3d(HairEyeColor$Hair, HairEyeColor$Freq,HairEyeColor$Sex)
#HEATMAP
distMatrix <- as.matrix(dist(HairEyeColor[,0:3]))
heatmap(distMatrix)

#DATASET(BOD)
View(BOD)
nrow(BOD)
ncol(BOD)
dim(BOD)
names(BOD)
str(BOD)
attributes(BOD)
head(BOD, 10) 
tail(BOD, 10)
BOD[1:10]
summary(BOD)
names(BOD)
attributes(BOD)
dim(BOD)
mean(BOD$demand)
median(BOD$demand)
quantile(BOD$demand)
range(BOD)
var(BOD)
hist(BOD$demand)
cov(BOD)
cor(BOD$demand,BOD$Time)
hist(BOD)



summary(EuStockMarkets)
names(EuStockMarkets)
attributes(EuStockMarkets)
dim(EuStockMarkets)
head(EuStockMarkets,10)
tail(EuStockMarkets,10)
mean(EuStockMarkets)
median(EuStockMarkets)
range(EuStockMarkets)
quantile(EuStockMarkets)
var(EuStockMarkets)
hist(EuStockMarkets)
table(EuStockMarkets)
plot(density(EuStockMarkets))
pie(table(EuStockMarkets))
barplot(table(EuStockMarkets))


View(AirPassengers)
nrow(AirPassengers)
ncol(AirPassengers)
dim(AirPassengers)
names(AirPassengers)
str(AirPassengers)
attributes(AirPassengers)
head(AirPassengers, 10) 
tail(AirPassengers, 10)
summary(AirPassengers)
names(AirPassengers)
attributes(AirPassengers)
dim(AirPassengers)
head(AirPassengers,10)
tail(AirPassengers,10)
mean(AirPassengers)
median(AirPassengers)
quantile(AirPassengers)
range(AirPassengers)
var(AirPassengers)
hist(AirPassengers)



nrow(USArrests)
attributes(USArrests)
ncol(USArrests)
head(USArrests, 10)
dim(USArrests)
tail(USArrests, 10)
names(USArrests)
str(USArrests)
USArrests$Murder[1:10]
summary(USArrests)
mean(USArrests$Murder)
median(USArrests$Murder)
range(USArrests$Murder)
quantile(USArrests$Murder)
quantile(USArrests$Murder, c(.1, .3, .65))
var(USArrests$Murder)
hist(USArrests$Murder)
plot(density(USArrests$Murder))
table(USArrests$Murder)
pie(table(USArrests$Murder))
barplot(table(USArrests$Murder))
cov(USArrests$Murder,USArrests$Assault)
cov(USArrests[,1:4])
cor(USArrests$Murder,USArrests$Assault)
library(scatterplot3d)
scatterplot3d(USArrests$Murder,USArrests$Assault,USArrests$UrbanPop)
distMatrix <- as.matrix(dist(USArrests[,0:3]))
heatmap(distMatrix)
